PictureGallery/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PictureGallery.Data;

namespace PictureGallery.Models
{
    public class AlbumsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlbumsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index()
        {
            var albums = _context.Album
                .Include(x => x.Favorites)
                .Include(p => p.User);
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(await albums.ToListAsync());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            foreach (var album in albums)
            {
                var currentFavorite = album.Favorites.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentFavorite != null)
                {
                    album.IsFavorite = currentFavorite.IsFavorite;
                }
            }
            return View(await albums.ToListAsync());
        }

        // Uus Index action kasutaja enda albumite vaatamiseks
        public IActionResult MyIndex()
        {
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Album.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Album> Albums = new List<Album>();
            // Võta ainult need albumid, mis on praeguse kasutaja omad
            Albums = _context.Album.Where(x => x.UserId == currentUserId).ToList();
            return View(Albums);
        }

        // GET: Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var album = await _context.Album
                .Include(x => x.User)
                .Include(x => x.Pictures)
                .Include(x => x.Favorites)
                .FirstOrDefaultAsync(m => m.Id == id);
            album.Pictures = album.Pictures.OrderByDescending(x => x.DateCreated).ToList();
            if (album == null)
            {
                return NotFound();
            }

            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(album);
            }
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            if (album.Favorites != null)
            {
                var currentFavorite = album.Favorites.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentFavorite != null)
                {
                    album.IsFavorite = currentFavorite.IsFavorite;
                }
            }

            return View(album);
        }

        // GET: Albums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,UserId,DateCreated")] Album album)
        {
            if (ModelState.IsValid)
            {
                // Küsib praeguse kasutaja
                ClaimsPrincipal currentUser = this.User;
                album.UserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MyIndex));
            }
            return View(album);
        }

        // GET: Albums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,UserId,DateCreated")] Album album)
        {
            if (id != album.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    // Muudetakse ainult albumi title
                    Album config = _context.Album.Find(album.Id);
                    config.Title = album.Title;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyIndex));
            }
            return View(album);
        }

        // GET: Albums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
                .FirstOrDefaultAsync(m => m.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Album.FindAsync(id);
            _context.Album.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyIndex));
        }

        private bool AlbumExists(int id)
        {
            return _context.Album.Any(e => e.Id == id);
        }
    }
}

PictureGallery/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PictureGallery.Data;
using PictureGallery.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace PictureGallery.Controllers
{
    public class PicturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PicturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pictures
        public async Task<IActionResult> Index()
        {
            // Näita Albumi Id asemel Albumi Title
            var applicationDbContext = _context.Picture
                                            .Include(p => p.Album)
                                            .Include(x => x.Likes)
                                            .OrderByDescending(x => x.DateCreated);
            var pictures = await applicationDbContext.ToListAsync();

            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Picture.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;

            foreach (var picture in pictures)
            {
                picture.AmountOfLikes =  picture.Likes.Where(x => x.IsLiked).Count();
                var currentLike = picture.Likes.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentLike != null)
                {
                    picture.IsLiked = currentLike.IsLiked;
                }
            }
            return View(pictures);
        }

        // Uus Index action kasutaja enda piltide vaatamiseks
        public IActionResult MyIndex()
        {
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Picture.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            List<Picture> Pictures = new List<Picture>();
            // Võta ainult need albumid, mis on praeguse kasutaja omad ja lisa albumid kaasa
            Pictures = _context.Picture
                .Where(x => x.Album.UserId == currentUserId)
                .Include(x => x.Album)
                .OrderByDescending(x => x.DateCreated).ToList();
            return View(Pictures);
        }
        // GET: Pictures/Details/5
        public IActionResult Details(int? id, int? albumId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pictures = _context.Picture
                .Include(x => x.Comments)
                    .ThenInclude(x => x.User)
                .Include(x => x.Album)
                    .ThenInclude(x => x.User)
                .Include(x => x.Likes)
                .OrderByDescending(x => x.DateCreated).ToList();
            if(albumId != null)
            {
                pictures = pictures.Where(x => x.Album.Id == albumId).ToList();
            }
            // Praegu vaadatav pilt on picture
            var picture = pictures.FirstOrDefault(m => m.Id == id);
            if (picture == null)
            {
                return NotFound();
            }
            picture.Comments = picture.Comments.OrderByDescending(x => x.DateCreated).ToList();

            var currentPictureIndex = pictures.IndexOf(picture);
            // Kui praegune pilt ei ole esimene, siis anna eelmise pildi ID kaasa
            if (currentPictureIndex > 0)
            {
                ViewBag.PreviousPictureId = pictures[pictures.IndexOf(picture) - 1].Id;
            }
            // Kui praegune pilt ei ole viimane, siis anna järgmise pildi ID kaasa
            if (currentPictureIndex != pictures.Count-1)
            {
                ViewBag.NextPictureId = pictures[pictures.IndexOf(picture) + 1].Id;
            }
            // Kui albumId on kaasas, siis anna see edasi kaasa (vaadatakse albumit)
            if (albumId != null)
            {
                ViewBag.AlbumId = albumId;
            }

            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(picture);
            }
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            if (picture.Likes != null)
            {
                var currentLike = picture.Likes.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentLike != null)
                {
                    picture.IsLiked = currentLike.IsLiked;
                }
            }
            return View(picture);
        }

        // Tagastab suure pildi
        public IActionResult GetImageFile(int pictureId)
        {
            var picture = _context.Picture.Find(pictureId);
            if (picture == null || picture.Image == null)
            {
                return Content("Picture not found.");
            }
            return File(picture.Image, "image/jpg");
        }
        // Tagastab thumbi või kui seda ei ole, siis suure pildi
        public IActionResult GetThumbnail(int pictureId)
        {
            var picture = _context.Picture.Find(pictureId);
            if (picture == null)
            {
                return Content("Picture not found.");
            }
            else if (picture.ImageThumbnail == null)
            {
                return GetImageFile(pictureId);
            }
            return File(picture.ImageThumbnail, "image/jpg");
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveComment(int pictureId, string commentText)
        {
            var comment = new Comment();
            if (commentText == null)
            {
                // Kui kommentaariväli on tühi, siis seda ei lisata
                ModelState.AddModelError("", "Please type a comment.");
                return RedirectToAction(nameof(Details), new { Id = pictureId });
            }
            comment.Content = commentText;
            comment.PictureId = pictureId;
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name != null)
            {
                comment.UserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            _context.Add(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { Id = pictureId });
        }

        // GET: Pictures/Create
        public IActionResult Create(int albumId)
        {
            // Pilt läheb sellesse albumisse, mille alt ta lisatakse
            ViewData["AlbumId"] = albumId;
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Image,ImageThumbnail,AlbumId,DateCreated")] Picture picture, IFormFile image)
        {
            var albumId = picture.AlbumId;
            ViewData["AlbumId"] = albumId;
            if (image == null)
            {
                ModelState.AddModelError("", "Image file required");
                return View(picture);
            }
            if (ModelState.IsValid)
            {
                MemoryStream stream = new MemoryStream();
                image.CopyTo(stream);

                IImageFormat format;
                // Max mõõtudest suurema pildi vähendamine
                using (Image<Rgba32> imageToResize = Image.Load(stream.ToArray(), out format))
                {
                    stream = new MemoryStream();
                    if (imageToResize.Width > 800)
                    {
                        imageToResize.Mutate(x => x.Resize(800, 0));
                    }
                    if (imageToResize.Height > 600)
                    {
                        imageToResize.Mutate(x => x.Resize(0, 600));
                    }
                    imageToResize.Save(stream, format);
                }
                picture.Image = stream.ToArray();

                //Thumbi genereerimine. Peab olema vähemalt 350 x 250 px ja piirav mõõt peab olema täpne
                using (Image<Rgba32> imageToResize = Image.Load(stream.ToArray(), out format))
                {
                    stream = new MemoryStream();
                    if (imageToResize.Width/(double)imageToResize.Height > 1.4 )
                    {
                        imageToResize.Mutate(x => x.Resize(0, 250));
                    }
                    else
                    {
                        imageToResize.Mutate(x => x.Resize(350, 0));
                    }
                    imageToResize.Save(stream, format);
                }
                picture.ImageThumbnail = stream.ToArray();
                stream.Close();

PictureGallery/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Authors: Joel Randveer, Eleen Soome, Villem Voormansik, Marilyn Võsu</p>

PictureGallery/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PictureGallery/Views/Home/Index.cshtml
@model PictureGallery.ViewModels.FirstPageContent

@{
    ViewData["Title"] = "PictureGallery";
}

<div class="column">
    <h4>New pictures:</h4>
    <div class="row">
        @foreach (var item in Model.NewestPictures)
        {
            <div class="col-sm-4">
                @if (item.Image != null)
                {
                <a asp-controller="Pictures" asp-action="Details" asp-route-id="@item.Id">
                    <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, }) 
                      alt= @item.Title, @item.Album.User.FirstName @item.Album.User.LastName 
                      title="@item.Title, by @item.Album.User.FirstName @item.Album.User.LastName"/>
                </a>
                }
            </div>
        }
    </div>
    <h4>Best pictures:</h4>
    <div class="row">
        @foreach (var item in Model.MostLikedPictures1stRow)
        {
            <div class="col-sm-4">
                @if (item.Image != null)
                {
                    <a asp-controller="Pictures" asp-action="Details" asp-route-id="@item.Id">
                        <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, }) 
                             alt= @item.Title, @item.Album.User.FirstName @item.Album.User.LastName 
                            title="@item.Title, by @item.Album.User.FirstName @item.Album.User.LastName"/>
                    </a>
                }
            </div>
        }
    </div>
    <div class="row">
        @foreach (var item in Model.MostLikedPictures2ndRow)
        {
        <div class="col-sm-4">
            @if (item.Image != null)
            {
                <a asp-controller="Pictures" asp-action="Details" asp-route-id="@item.Id">
                    <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, })
                         alt=@item.Title , @item.Album.User.FirstName @item.Album.User.LastName
                        title="@item.Title, by @item.Album.User.FirstName @item.Album.User.LastName" />
                </a>
            }
        </div>
        }
    </div>
    <h4>New albums:</h4>
    <div class="row">
        @foreach (var item in Model.NewestAlbumCoverPictures)
        {
        <div class="col-sm-4">
            @item.Album.User.FirstName
            @item.Album.User.LastName:
            <a asp-controller="Albums" asp-action="Details" asp-route-id="@item.Album.Id">
                <i>@item.Album.Title</i>
                <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, }) 
                    alt= @item.Album.Title, @item.Album.User.FirstName @item.Album.User.LastName 
                    title="Album: @item.Album.Title, by @item.Album.User.FirstName @item.Album.User.LastName"/>
            </a>
        </div>
        }
    </div>
    <h4>Best albums:</h4>
    <div class="row">
        @foreach (var item in Model.BestAlbumCoverPictures)
        {
        <div class="col-sm-4">
            @item.Album.User.FirstName
            @item.Album.User.LastName:
                <a asp-controller="Albums" asp-action="Details" asp-route-id="@item.Album.Id">
                    <i>@item.Album.Title</i>
                    <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, }) 
                         alt= @item.Album.Title, @item.Album.User.FirstName @item.Album.User.LastName 
                         title="Album: @item.Album.Title, by @item.Album.User.FirstName @item.Album.User.LastName"/>
                </a>
        </div>
        }
    </div>